pipeline {
    agent any

    environment {
        VENV_DIR = "${WORKSPACE}/venv"
        PYTHON = "python3"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:Cavein254/alx-backend-python.git',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Setup Environment') {
            steps {
                sh '''
                  # Change to project directory
                  cd ${WORKSPACE}/alx-backend-python/messaging_app
                  # Create virtual environment
                  ${PYTHON} -m venv ${VENV_DIR}
                  . ${VENV_DIR}/bin/activate

                  # Upgrade pip
                  pip3 install --upgrade pip

                  # Install project dependencies
                  pip3 install -r messaging_app/requirements.txt

                  # Install pytest and junitxml plugin for reporting
                  pip3 install pytest pytest-django pytest-cov pytest-html
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                  . ${VENV_DIR}/bin/activate
                  cd ${WORKSPACE}/alx-backend-python/messaging_app
                  pytest --maxfail=1 --disable-warnings -q                          --junitxml=report.xml                          --html=report.html --self-contained-html
                '''
            }
        }

        stage('Archive Reports') {
            steps {
                junit 'report.xml'
                archiveArtifacts artifacts: 'report.html', fingerprint: true
            }
        }
    }
}